import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
const page = readFileSync("src/pages/Login/LoginPage.tsx", "utf8");
const form = readFileSync("src/features/auth/components/LoginForm.tsx", "utf8");
assert.equal(page.includes("max-w-md"), true);
assert.equal(page.includes("rounded-3xl"), true);
assert.equal(page.includes("backdrop-blur-xl"), true);
assert.equal(page.includes("lg:grid-cols"), true);
assert.equal(form.includes('htmlFor="login-email"'), true);
assert.equal(form.includes('htmlFor="login-password"'), true);
assert.equal(form.includes('autoComplete="email"'), true);
assert.equal(form.includes('autoComplete="current-password"'), true);
assert.equal(form.includes('aria-live="polite"'), true);
assert.equal(form.includes("getSafeRedirectPath"), true);
assert.equal(form.includes("showPassword"), true);
assert.equal(form.includes("disabled={submitting}"), true);
assert.equal(existsSync("src/pages/Login.tsx"), false);
assert.equal(/console\.(log|error|warn).*?(password|token|authorization)/i.test(page + form), false);
console.log(JSON.stringify({ suite: "loginInterface", passed: 14, failed: 0, modernResponsiveShell: true, accessibleLabels: true, safeRedirectPreserved: true, routeGuardBypassed: false, legacyDebugLoginRemoved: true }, null, 2));
