import pool from "../config/db.js";
import { canTransitionBooking } from "../utils/adminStatusTransitions.js";
const failure=(res,status,code,message)=>res.status(status).json({success:false,code,message});
export async function getAdminStats(req,res){try{const [cars,bookings,users,pendingBookings,pendingListings]=await Promise.all([pool.query("SELECT COUNT(*)::int AS count FROM cars"),pool.query("SELECT COUNT(*)::int AS count FROM bookings"),pool.query("SELECT COUNT(*)::int AS count FROM users"),pool.query("SELECT COUNT(*)::int AS count FROM bookings WHERE status = $1",["pending"]),pool.query("SELECT COUNT(*)::int AS count FROM cars WHERE LOWER(status) = $1",["pending"])]);return res.status(200).json({success:true,data:{totalCars:cars.rows[0].count,totalBookings:bookings.rows[0].count,totalUsers:users.rows[0].count,pendingBookings:pendingBookings.rows[0].count,pendingListings:pendingListings.rows[0].count},timestamp:new Date().toISOString()});}catch(error){console.error("Admin stats failed:",error);return failure(res,500,"ADMIN_STATS_FAILED","Admin statistics could not be loaded.");}}
export async function getAllBookings(req,res){try{const result=await pool.query(`SELECT b.*,u.name AS user_name,u.email AS user_email,c.make,c.model,c.year FROM bookings b LEFT JOIN users u ON b.user_id=u.id LEFT JOIN cars c ON b.car_id=c.id ORDER BY b.created_at DESC`);return res.status(200).json({success:true,data:result.rows,total:result.rowCount});}catch(error){console.error("Admin bookings failed:",error);return failure(res,500,"ADMIN_BOOKINGS_FAILED","Bookings could not be loaded.");}}
export async function updateBookingStatus(req,res){const id=req.adminResourceId;const status=req.adminBookingStatus;const expected=req.body?.expectedUpdatedAt;try{const current=await pool.query("SELECT * FROM bookings WHERE id = $1 LIMIT 1",[id]);if(!current.rowCount)return failure(res,404,"BOOKING_NOT_FOUND","Booking was not found.");const booking=current.rows[0];if(!canTransitionBooking(String(booking.status).toLowerCase(),status))return failure(res,409,"INVALID_TRANSITION",`Booking cannot move from ${booking.status} to ${status}.`);if(expected&&new Date(booking.updated_at).toISOString()!==new Date(expected).toISOString())return failure(res,409,"STALE_STATE","Booking changed on the server. Refresh and try again.");const updated=await pool.query("UPDATE bookings SET status = $1, updated_at = NOW() WHERE id = $2 RETURNING *",[status,id]);return res.status(200).json({success:true,message:"Booking status updated.",data:updated.rows[0]});}catch(error){console.error("Admin booking update failed:",error);return failure(res,500,"BOOKING_UPDATE_FAILED","Booking status could not be updated.");}}
export async function getPendingApprovals(req,res){try{const result=await pool.query("SELECT * FROM cars WHERE LOWER(status) = $1 ORDER BY created_at DESC",["pending"]);return res.status(200).json({success:true,data:result.rows,total:result.rowCount});}catch(error){console.error("Pending listings failed:",error);return failure(res,500,"PENDING_LISTINGS_FAILED","Pending listings could not be loaded.");}}
export async function approveVehicle(req,res){try{const result=await pool.query("UPDATE cars SET status = $1, approved_at = NOW(), rejection_reason = NULL, updated_at = NOW() WHERE id = $2 AND LOWER(status) = $3 RETURNING *",["approved",req.adminResourceId,"pending"]);if(!result.rowCount)return failure(res,404,"LISTING_NOT_FOUND","Pending listing was not found.");return res.status(200).json({success:true,message:"Listing approved.",data:result.rows[0]});}catch(error){console.error("Listing approval failed:",error);return failure(res,500,"LISTING_APPROVAL_FAILED","Listing could not be approved.");}}
export async function rejectVehicle(req,res){try{const result=await pool.query("UPDATE cars SET status = $1, rejection_reason = $2, approved_at = NULL, updated_at = NOW() WHERE id = $3 AND LOWER(status) = $4 RETURNING *",["rejected",req.adminRejectionReason,req.adminResourceId,"pending"]);if(!result.rowCount)return failure(res,404,"LISTING_NOT_FOUND","Pending listing was not found.");return res.status(200).json({success:true,message:"Listing rejected.",data:result.rows[0]});}catch(error){console.error("Listing rejection failed:",error);return failure(res,500,"LISTING_REJECTION_FAILED","Listing could not be rejected.");}}
