import express from "express";
import { authenticateToken, checkRole } from "../middleware/authMiddleware.js";
import { validatePositiveId, validateBookingStatusBody, validateListingRejectionBody } from "../middleware/validateAdminOperation.js";
import { getAdminStats,getAllBookings,updateBookingStatus,getPendingApprovals,approveVehicle,rejectVehicle } from "../controllers/adminController.js";
const router=express.Router();
const adminOnly=[authenticateToken,checkRole(["admin"])];
router.get("/stats",...adminOnly,getAdminStats);
router.get("/bookings",...adminOnly,getAllBookings);
router.patch("/bookings/:id/status",...adminOnly,validatePositiveId,validateBookingStatusBody,updateBookingStatus);
router.get("/listings/pending",...adminOnly,getPendingApprovals);
router.patch("/listings/:id/approve",...adminOnly,validatePositiveId,approveVehicle);
router.patch("/listings/:id/reject",...adminOnly,validatePositiveId,validateListingRejectionBody,rejectVehicle);
export default router;
