import { useEffect, useRef } from "react";
import type { AdminListingReview } from "../types";
import { ListingStatusBadge } from "./ListingStatusBadge";
export function ListingReviewDialog({ listing, onClose, onApprove, onReject, pending }: { listing: AdminListingReview | null; onClose: () => void; onApprove: () => void; onReject: () => void; pending: boolean }) {
  const closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (listing) closeRef.current?.focus(); }, [listing]);
  if (!listing) return null;
  const details = [["Listing ID", listing.id], ["Make and model", `${listing.make} ${listing.model}`.trim()], ["Year", listing.year ?? "Unavailable"], ["Price", listing.price ?? "Unavailable"], ["Mileage", listing.mileage ?? "Unavailable"], ["Condition", listing.condition ?? "Unavailable"], ["Images", "Image availability is not supplied by the normalized record"], ["Submitted", listing.createdAt ?? "Unavailable"]];
  return <div className="fixed inset-0 z-40 grid place-items-center bg-black/50 p-4"><section role="dialog" aria-modal="true" aria-labelledby="listing-review-title" className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-background p-6"><div className="flex items-start justify-between gap-4"><div><h2 id="listing-review-title" className="text-2xl font-bold">Review listing</h2><ListingStatusBadge status={listing.status} /></div><button ref={closeRef} type="button" disabled={pending} onClick={onClose} aria-label="Close listing review">Close</button></div><dl className="mt-6 grid gap-4 sm:grid-cols-2">{details.map(([label, value]) => <div key={String(label)} className="rounded-lg border p-3"><dt className="text-sm text-muted-foreground">{label}</dt><dd className="mt-1 font-semibold">{String(value)}</dd></div>)}</dl>{listing.rejectionReason && <p className="mt-4 rounded-md border p-3">Existing rejection reason: {listing.rejectionReason}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" disabled={pending} onClick={onReject} className="rounded-md border px-4 py-2">Reject</button><button type="button" disabled={pending} onClick={onApprove} className="rounded-md bg-primary px-4 py-2 text-primary-foreground">Approve</button></div></section></div>;
}
