import { clearStoredSession, getAuthToken as getCanonicalAuthToken } from "../features/auth/services/authStorage";
export const isUserAuthenticated=(state)=>Boolean(state?.isAuthenticated&&state?.user);
export const hasRequiredRole=(state,role)=>isUserAuthenticated(state)&&state.user?.role===role;
export const hasAnyRole=(state,roles=[])=>isUserAuthenticated(state)&&Array.isArray(roles)&&roles.includes(state.user?.role);
export const isTokenValid=()=>Boolean(getCanonicalAuthToken());
export const getAuthToken=getCanonicalAuthToken;
export const canAccessAdmin=(state)=>isUserAuthenticated(state)&&state.user?.role==="admin";
export const canAccessDealer=(state)=>isUserAuthenticated(state)&&["dealer","admin"].includes(state.user?.role);
export const clearAuthData=clearStoredSession;
export const storeAuthData=()=>{ throw new Error("Use the canonical authentication context to save sessions."); };
